### ISSUE TITLE
Mesh refactoring

### ISSUE THREAD

**Issue by tcreusc** [SwanLab/Swan#179]
**Phase 1: Mesh**
Status: @tcreusc to start working in it
Tasks
- [x] Check if STL stuff still works #291 
- [x] Move: Geometry directly to Mesh #308  
- [x] Remove: createFromFile, setCoord, setConnec, coordElem #292 #293 
- [x] Generalize: computeMinCellSize, computeMeanCellSize #294 
- [x] Refactor: plot, LineMesh, SurfaceMesh, VolumeMesh #295 

Notes
- kFace!! changes Geometry calculations
- Normals only when kFace = -1 
- Can xFE become a P1Function instead of a P1Discontinuous?

**Phase 2: SubMesh**
Status: @FerrerFerreAlex to further investigate on it
Notes
- Create Submesh < Mesh, with 
- P1Functions locally, LHS/RHS should be able to manage local to global. LHS should still be able to assemble locally.
- If test and trial belong to the same space, local. If test and trial do not, globally.
- innerMesh, innerCut, boundaryCut, ... are instances of Submesh
- P1Function can be created with a Submesh, when creating connec there could be two options (local/global)
